plugins:
  - jekyll-feed
  - jekyll-sitemap
theme: jekyll-theme-hacker
author: Mike Levin
permalink: /:slug/
gaid: G-ZNMVJFLRD2
title: Linux, Python, vim & git | LinuxPythonvimgit.com
description: Welcome to the Linux, Python, vim & git | LinuxPythonvimgit.com Website!
tagline: Linux, Python, vim & git
welcome: Welcome to the Linux, Python, vim & git Website!
apex: LinuxPythonvimgit.com